### ISSUE TITLE
Compile error on macOS

### ISSUE THREAD

**Issue by Hustwireless** [cmm-21/a1#1]
Hi,

I've got an error when compiling the code on the macOS, the error message is like this:

> [ 76%] Linking CXX static library libkinematics.a
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make[2]: *** [src/kinematics/libkinematics.a] Error 1
make[1]: *** [src/kinematics/CMakeFiles/kinematics.dir/all] Error 2
make: *** [all] Error 2

Any idea how to fix this? Thanks!

**Comment by Glanfaloth** [comment]
You have to add a .cpp file in ./src/kinematics/

**Comment by moritzge** [comment]
it should be an empty file. 

For example, in the starter code repo, I added src/kinematics/dummy.cpp 
https://github.com/cmm-21/a1/tree/master/src/kinematics/dummy.cpp
