### ISSUE TITLE
Handing in the Assignment

### ISSUE THREAD

**Issue by deltahue** [cmm-21/a1#12]
Dear TAs

How do we need to hand in the assignment? Do we just need to push our changes before the deadline to our repos?

Best,
David

**Comment by Maenzgi** [comment]
I have the same question, because I have very limited experience with github. If the right version shows up in https://github.com/cmm-21/a1-[MyName], did the hand-in work?

Best,
Manuel

**Comment by moritzge** [comment]
Yes. You push your solution to github.com before the deadline. 

You can check your commits here: https://github.com/cmm-21/a1-[YOUR_NAME]/commits/master

**Comment by deltahue** [comment]
Thanks!
