### ISSUE TITLE
All tests passed on local but not on GitHub

### ISSUE THREAD

**Issue by sirkrisp** [cmm-21/a1#14]
Hi, all tests pass on my local machine (and everything works inside the linkage app as it should) but for some reason, the last test does not pass on GitHub.

Do you have any ideas?

Thanks in advance!

**Comment by moritzge** [comment]
Hi,

According to the test run on github, your implementation of the Hessian is incorrect:
```
 1: test_6_IKHessian............................................FAILED (error = 16.6798 > tol = 1e-08)
  1: groundTruth != ik.hessian(x)
  1: groundTruth: 
  1:  -1.42485 -0.669112
  1: -0.669112  -2.13921
  1: ik.hessian(x): 
  1: 10.2617 6.20206
  1: 6.20206 4.73196
  1: difference: 
  1: -11.6866 -6.87117
  1: -6.87117 -6.87117
```

Are you sure you pushed all changes?

**Comment by moritzge** [comment]
I cloned your code and ran it on my machine (Linux, gcc 10). I get the same results as on github.com.

**Comment by sirkrisp** [comment]
Hm, interesting, I just cloned from GitHub to go sure and all tests passed again on my machine (on MacOs with Apple M1, clang 12.0.0 with target arm64-apple-darwin20.3.0)
<img width="858" alt="Bildschirmfoto 2021-03-18 um 12 33 22" src="https://user-images.githubusercontent.com/43377824/111619837-4f718680-87e6-11eb-8827-d1862bac91a8.png">

**Comment by sirkrisp** [comment]
Ok it turns out 

```c++
auto v = forwardKinematics(*linkage, x)[2] - *target;
```
works as expected on clang but for some reason not on gcc. This works on gcc:
```c++
Vector2d v = forwardKinematics(*linkage, x)[2];
v -= (*target);
```
If someone knows why I would appreciate it if you could comment. Thanks!
