### ISSUE TITLE
fatal error LNK1181: cannot open input file '..\kinematics\Release\kinematics.lib'

### ISSUE THREAD

**Issue by madBot42** [cmm-21/a1#6]
Hi,

it cannot seem to find/open the kinematics library and googling the error LNK1181 and implementing suggested solutions didn't really help.. What could be the problem?

Error message 1:
`[build]   optimization.vcxproj -> C:\Users\madtop\polybox\ETHMaster\FS21\CMM\a1-madBot42\build\src\optimization\Release\optimization.lib`
`[build] LINK : fatal error LNK1181: cannot open input file '..\kinematics\Release\kinematics.lib' [C:\Users\madtop\polybox\ETHMaster\FS21\CMM\a1-madBot42\build\src\test-a1\test-a1.vcxproj]`
`[build] Build finished with exit code 1`

Sometimes it's also this one:
`[build]   glad.vcxproj -> C:\Users\madtop\polybox\ETHMaster\FS21\CMM\a1-madBot42\build\ext\glad\Release\glad.lib`
`[build]   glfw.vcxproj -> C:\Users\madtop\polybox\ETHMaster\FS21\CMM\a1-madBot42\build\ext\ext\glfw\src\Release\glfw3.lib`
`[build]   optimization.vcxproj -> C:\Users\madtop\polybox\ETHMaster\FS21\CMM\a1-madBot42\build\src\optimization\Release\optimization.lib`
`[build]   nanovg.vcxproj -> C:\Users\madtop\polybox\ETHMaster\FS21\CMM\a1-madBot42\build\ext\Release\nanovg.lib`
`[build]   imgui.vcxproj -> C:\Users\madtop\polybox\ETHMaster\FS21\CMM\a1-madBot42\build\ext\Release\imgui.lib`
`[build]   gui.vcxproj -> C:\Users\madtop\polybox\ETHMaster\FS21\CMM\a1-madBot42\build\src\gui\Release\gui.lib`
`[build] LINK : fatal error LNK1181: cannot open input file '..\kinematics\Release\kinematics.lib' [C:\Users\madtop\polybox\ETHMaster\FS21\CMM\a1-madBot42\build\src\test-a1\test-a1.vcxproj]`
`[build] LINK : fatal error LNK1181: cannot open input file '..\kinematics\Release\kinematics.lib' [C:\Users\madtop\polybox\ETHMaster\FS21\CMM\a1-madBot42\build\src\app\linkage-app.vcxproj]`
`[build] Build finished with exit code 1`

Thanks :)

Greetings
Madeleine

**Comment by liyuesolo** [comment]
Please check the issue #2 to clone the new initial code.

**Comment by madBot42** [comment]
Thank you very much for the quick answer! It works now :)
