### ISSUE TITLE
Task2: In which order should the dimensions of the Hessian tensor be arranged?

### ISSUE THREAD

**Issue by Zzyus** [cmm-21/a1#7]
To pass test 3 in Task 2, it seems like we need to arrange the Hessian tensor in the form of [x_i, f, x_j]. What's the reason behind this?  Because this is a little bit non-intuitive since the dimension that corresponds to f is put in the middle, not like [f, x_i, x_j] nor [x_i, x_j, f]. Also, it makes the computation in Task 3.3 more complicated, since we won't be able to directly do tensor multiplication then.

**Comment by moritzge** [comment]
Are you talking about this test? https://github.com/cmm-21/a1/blob/a46c4275e0c60d362ed42c2dc9827502fc70ae51/src/test-a1/test.cpp#L50

In the following, I will use angles x and end-effector position e(x).
- x is a vector of size 2
- e is a vector of size 2
- de/dx is a matrix of size 2x2, where the entry i,j corresponds to de_i/dx_j
- d^2e/dx^2 is a tensor of size 2x2x2, implemented as an array of two matrices. The matrix with index k is d (de/dx) / dx_k.

Does this help?

**Comment by Zzyus** [comment]
Ah yes, it does make sense. Thank you!
