### ISSUE TITLE
Assignment 1 : grading

### ISSUE THREAD

**Issue by lthiet** [cmm-21/a1#8]
Dear TA team,

Would it be possible to let us know what is expected to get correctness for the assignment. Because we did not have to implement the Newton's Method optimizer, can we be ok with not reaching local minima provided all tests pass?

**Comment by moritzge** [comment]
Hi,

You have to compute all quantities analytically. The code you write has to compute the correct result for any input. For example, in Task 3, you have to compute the correct objective function and its gradient and Hessian. If your implementation in code computes them correctly for any given pair of angles (and analytically), you will get full points.

Does this answer your question?

**Comment by lthiet** [comment]
yes, thank you
